---
title: "nhl_stats"
output: html_document
date: "2022-07-27"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F)
```

```{r}
library(tidyverse)
library(nhlapi)
library(reactable)

```

```{r}
# get full red wings roster info for 21/22 season
wings_roster = nhlapi::nhl_teams_rosters(teamIds = 17, seasons = "20222023")

# get specific roster info
players = wings_roster[[30]][[1]]

# change column to be same name as other tables
colnames(players)[2] = "playerId"

# create vector of only players ids
player_ids = players$playerId

########################################

# get season stats

#season_team_stats = nhlapi::nhl_teams_stats(teamIds = 17, seasons = "20222023")
#^^ not quite what we wanted, but that's ok

# let's try again
season_stats = nhlapi::nhl_players_seasons(seasons = "20222023", playerIds = player_ids)
  
wings_player_sea_stats_full = merge(season_stats, players, by = "playerId")

sea_stats = wings_player_sea_stats_full %>% 
  dplyr::select(-c("url", 
            "copyright", 
            "seasonStart", 
            "person.link", 
            "position.code", 
            "position.name",
            "position.type"))

skaters = sea_stats %>% 
  dplyr::filter(position.abbreviation != "G")

#summary(skaters)

skaters = skaters %>% 
  dplyr::select(-c("stat.ot", 
            "stat.shutouts", 
            "stat.ties", 
            "stat.wins", 
            "stat.losses", 
            "stat.saves", 
            "stat.powerPlaySaves", 
            "stat.shortHandedSaves", 
            "stat.evenSaves", 
            "stat.shortHandedShots", 
            "stat.evenShots", 
            "stat.powerPlayShots", 
            "stat.savePercentage", 
            "stat.goalAgainstAverage", 
            "stat.gamesStarted", 
            "stat.shotsAgainst", 
            "stat.goalsAgainst", 
            "stat.powerPlaySavePercentage", 
            "stat.shortHandedSavePercentage", 
            "stat.evenStrengthSavePercentage"))

goalies = sea_stats %>% 
  dplyr::filter(position.abbreviation == "G")

goalies = goalies[,colSums(is.na(goalies)) != 4]

#summary(goalies)

```



```{r}
# skater_cols = c(stat.timeOnIce, 
#                 stat.assists, 
#                 stat.goals, 
#                 stat.pim, 
#                 stat.shots, 
#                 stat.games, 
#                 stat.hits, 
#                 stat.powerPlayGoals, 
#                 stat.powerPlayPoints,  
#                 stat.powerPlayTimeOnIce, 
#                 stat.evenTimeOnIce, 
#                 stat.penaltyMinutes, 
#                 stat.faceOffPct, 
#                 stat.shotPct, 
#                 stat.gameWinningGoals, 
#                 stat.overTimeGoals, 
#                 stat.shorthandedGoals, 
#                 stat.shortHandedPoints, 
#                 stat.shortHandedTimeonIce, 
#                 stat.blocked, 
#                 stat.plusMinus, 
#                 stat.Points, 
#                 stat.shifts, 
#                 stat.timeOnIcePerGame, 
#                 stat.evenTimeOnIcePerGame, 
#                 stat.shortHandedTimeOnIcePerGame,
#                 stat.powerPlayTimeOnIcePerGame, 
#                 jerseyNumber, 
#                 person.fullName, 
#                 position.abbreviation)


skater_table = skaters %>% 
  dplyr::select(c(
                jerseyNumber,
                person.fullName,
                stat.timeOnIce,
                stat.shots,
                stat.goals, 
                stat.shotPct, 
                stat.assists, 
                stat.points,  
                stat.pim, 
                stat.shifts,
                stat.timeOnIcePerGame, 
                stat.evenTimeOnIce,
                stat.evenTimeOnIcePerGame,   
                stat.powerPlayTimeOnIce,
                stat.powerPlayTimeOnIcePerGame,
                stat.shortHandedTimeOnIce,
                stat.shortHandedTimeOnIcePerGame, 
                stat.games, 
                stat.hits, 
                stat.powerPlayGoals, 
                stat.powerPlayPoints,
                stat.penaltyMinutes, 
                stat.faceOffPct,
                stat.gameWinningGoals, 
                stat.overTimeGoals, 
                stat.shortHandedGoals, 
                stat.shortHandedPoints, 
                stat.blocked, 
                stat.plusMinus, 
                
                
                
                  
                position.abbreviation))

reactable(skater_table, defaultSorted = list(stat.goals = "desc"))

#reactable(skaters, defaultSorted = list(stat.goals = "desc"))
```



































